### PR TITLE
Order baremetal with BareMetalServerOrder classs of Ruby Softlayer API

### PR DESCRIPTION
**Pull request by jianqiu**
more simple and convenience.

### CODE REVIEW

**Comment by jianqiu** [comment]
@maximilien, @JimmyMa

Could you please review this PR? Thanks!

**Comment by maximilien** [comment]
Seems to be duplicate of #2

**Comment by jianqiu** [comment]
@maximilien 
I just closed another one and keep this one for review, thanks!

**Comment by maximilien** [comment]
Merging. However, very sad 😢  that we have no tests for this code base...  I will figure out a way to fix this situation soon.

**Pull request merged**
